---
  ansible_user: "jack"
  k3s_version: v1.20.8+k3s1
  systemd_dir: /etc/systemd/system
  master_ip: "{{ hostvars[groups['masters'][0]]['ansible_host'] | default(groups['masters'][0]) }}"
  extra_server_args: ""
  extra_agent_args: ""